baseURL = "https://pilm-bioinformatics.github.io/knowledgebase/"
theme = "dot"
publishDir = "docs"

[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "PILM Bioinformatics KnowledgeBase"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "Dot"
  copyright = "The Hugo Documents are copyright Â© gethugothemes 2018."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Faq"
        url = "/faq"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "contact"
        url = "https://github.mit.edu/PILM-bioinformatics/support/issues/new"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "pages"
        url = "/pages"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Environment"
          URL = "/environment"
          weight = 1

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Analysis Type"
          URL = "/analysis"
          weight = 2

    # banner
    [Languages.en.params.banner]
      title = "Knowledge base"
      description = "Find advice and answers or get in touch"
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Find your answer by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Open an issue with your query."
      btnText = "contact us"
      btnURL = "https://github.mit.edu/PILM-bioinformatics/support/issues/new"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      URL = "@lopantano"
      
